apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: pro
spec:
    ports:
        - name: "80"
          nodePort: 30001
          port: 80
          protocol: TCP
          targetPort: 80
        - name: "81"
          nodePort: 30002
          port: 81
          protocol: TCP
          targetPort: 81
        - name: "443"
          nodePort: 30003
          port: 443
          protocol: TCP
          targetPort: 443
    selector:
        app: nginx
    type: NodePort
