apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: skywalking-oap
    namespace: efk
    labels:
        app: skywalking-oap
spec:
    revisionHistoryLimit: 0
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: skywalking-oap
        spec:
            containers:
                - image: wutang/skywalking-oap:6.1.0
                  name: skywalking-oap
                  imagePullPolicy: Always
                  resources: {}
                  env:
                      - name: SW_STORAGE
                        value: elasticsearch
                      - name: SW_STORAGE_ES_CLUSTER_NODES
                        value: es-elasticsearch.efk:9200
                      - name: SW_STORAGE_ES_RECORD_DATA_TTL
                        value: "1"
                      - name: SW_STORAGE_ES_OTHER_METRIC_DATA_TTL
                        value: "1"
                      - name: SW_STORAGE_ES_MONTH_METRIC_DATA_TTL
                        value: "1"
                  ports:
                      - containerPort: 11800
                      - containerPort: 12800
                  volumeMounts:
                      - name: application
                        mountPath: /apache-skywalking-apm-bin/config/application.yml
                        subPath: application.yml
            restartPolicy: Always
            volumes:
                - name: application
                  configMap:
                      name: skywalking-config
