apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: skywalking-ui
    namespace: efk
    labels:
        name: skywalking-ui
spec:
    revisionHistoryLimit: 0
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                name: skywalking-ui
        spec:
            restartPolicy: Always
            containers:
                - image: skywalking/ui
                  name: skywalking-ui
                  resources: {}
                  env:
                      - name: SW_OAP_ADDRESS
                        value: skywalking-oap-service.efk:12800
                  ports:
                      - containerPort: 8080
