apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: skywalking-ui
    namespace: efk
    labels:
        app: skywalking-ui
spec:
    revisionHistoryLimit: 0
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: skywalking-ui
        spec:
            restartPolicy: Always
            containers:
                - image: wutang/skywalking-ui:6.1.0
                  name: skywalking-ui
                  resources: {}
                  env:
                      - name: collector.ribbon.listOfServers
                        value: "skywalking-oap-service.efk:12800"
                  ports:
                      - containerPort: 8080
